-  
   name: "install the nodejs and configure"
   hosts: all
   become: yes
   tasks:
    - name: Install npm and nodejs 
      apt: 
        name:
          - npm
          - nodejs
          - git
        state: present
        update_cache: true

    - name: Install npm forever package (to make the app always up)
      npm: name=forever global=yes state=present 

    - name: Check list of app.js apps running
      command: forever list
      register: forever_list
      changed_when: yes

    - name: See Console
      debug: var=forever_list.stdout_lines

    - name: cloning the git repository
      git: repo=git://github.com/abkunal/Chat-App-using-Socket.io.git  dest=/srv/DevOps clone=yes update=yes

